### ISSUE TITLE
Shouldn't we have a seprate repository for website

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/PyJaipur#21]
currently, the website is on pyjaipur/pyjaipur/website.  which on first place is hard to find also issues get merged with other topics such talks etc.

**Comment by theSage21** [comment]
We could but it's a lot easier to maintain right now. Otherwise everything is scattered everywhere. In the future if our website takes up more roles other than just displaying static information we could separate out those roles into other projects.

Right now this is the main information repo for pyjaipur.

**Comment by Shivank98** [comment]
Got it.
